import { createStorage } from 'wagmi';
import { WagmiAdapter } from '@reown/appkit-adapter-wagmi';
import { mainnet, base, celo, linea, optimism, sei } from '@reown/appkit/networks';
import type { Chain } from 'viem';

// This is a public demo project ID from WalletConnect.
// For a production application, you should get your own project ID from https://cloud.walletconnect.com/
// and set it as VITE_PROJECT_ID in your .env.local file.
export const projectId = import.meta.env.VITE_PROJECT_ID || '2b73abf5eb497019fbadec99ca8d2b8b';

if (!projectId) {
  throw new Error('VITE_PROJECT_ID is not defined. Please set it in .env.local');
}

// Define supported networks, explicitly typed as a non-empty array of Chains
// A subset of the original chains are included here for compatibility with Reown AppKit's standard network exports.
export const networks: [Chain, ...Chain[]] = [mainnet, base, celo, linea, optimism, sei];

// Create the Wagmi adapter instance for a client-side rendered (CSR) app
export const wagmiAdapter = new WagmiAdapter({
  storage: createStorage({ storage: window.localStorage }),
  ssr: false, // This is a client-side app
  projectId,
  networks,
});

// Export the Wagmi config generated by the adapter
export const config = wagmiAdapter.wagmiConfig;
